export const propertyCopy = {
  fr: {
    title: 'Trouvez votre appartement', intro: 'Comparez les appartements à Tunis et Sfax selon votre budget, votre surface et vos envies.',
    search: 'Ville, résidence ou référence', city: 'Ville', project: 'Résidence', all: 'Tous', status: 'Disponibilité',
    bedrooms: 'Chambres (hors séjour)', minPrice: 'Budget min. (TND)', maxPrice: 'Budget max. (TND)', minArea: 'Surface min. (m²)', maxArea: 'Surface max. (m²)',
    available: 'Disponible', reserved: 'Réservé', sold: 'Vendu', unconfirmed: 'Disponibilité à confirmer', reset: 'Réinitialiser', results: 'appartements',
    sort: 'Trier par', reference: 'Référence', priceAsc: 'Prix croissant', priceDesc: 'Prix décroissant', areaAsc: 'Surface croissante', areaDesc: 'Surface décroissante',
    empty: 'Aucun appartement ne correspond à ces critères.', request: 'Prix sur demande', details: 'Voir cet appartement',
    favourite: 'Ajouter aux favoris', unfavourite: 'Retirer des favoris', compare: 'Comparer', compared: 'Retirer du comparatif',
    selection: 'Ma sélection', favourites: 'Favoris', comparison: 'Comparaison', maxCompare: 'Vous pouvez comparer jusqu’à 3 appartements. Retirez-en un pour en ajouter un autre.',
    savedHere: 'Votre sélection est conservée sur cet appareil.', noSaved: 'Votre sélection est vide. Enregistrez des appartements depuis la recherche ou leur fiche.',
    storageError: 'La sélection reste disponible dans cet onglet, mais ce navigateur ne permet pas son enregistrement.',
    visit: 'Demander une visite', map: 'Voir la carte', mapHint: 'Localisation indicative par adresse. Le lieu exact du rendez-vous sera confirmé par notre équipe.',
    mapSelect: 'Résidence à afficher sur la carte', mapExternal: 'Ouvrir dans Google Maps', more: 'Afficher plus',
    floor: 'Étage', garden: 'Jardin', terrace: 'Terrasse', progress: 'Avancement', surface: 'Surface vendable', price: 'Prix',
    removed: 'Certains appartements enregistrés ne figurent plus au catalogue.',
  },
  en: {
    title: 'Find your apartment', intro: 'Compare apartments in Tunis and Sfax by budget, floor area and preferences.',
    search: 'City, residence or reference', city: 'City', project: 'Residence', all: 'All', status: 'Availability',
    bedrooms: 'Bedrooms (excluding living room)', minPrice: 'Min. budget (TND)', maxPrice: 'Max. budget (TND)', minArea: 'Min. area (m²)', maxArea: 'Max. area (m²)',
    available: 'Available', reserved: 'Reserved', sold: 'Sold', unconfirmed: 'Availability to confirm', reset: 'Reset', results: 'apartments', sort: 'Sort by', reference: 'Reference',
    priceAsc: 'Lowest price', priceDesc: 'Highest price', areaAsc: 'Smallest area', areaDesc: 'Largest area', empty: 'No apartments match these criteria.', request: 'Price on request', details: 'View apartment',
    favourite: 'Save to favourites', unfavourite: 'Remove from favourites', compare: 'Compare', compared: 'Remove from comparison',
    selection: 'My selection', favourites: 'Favourites', comparison: 'Comparison', maxCompare: 'Compare up to 3 apartments. Remove one before adding another.',
    savedHere: 'Your selection is saved on this device.', noSaved: 'Your selection is empty. Save apartments from the search or their details page.', storageError: 'Your selection is available in this tab, but this browser cannot save it.',
    visit: 'Request a visit', map: 'Show map', mapHint: 'Approximate address location. Our team will confirm the exact meeting point.', mapSelect: 'Residence to show on map', mapExternal: 'Open in Google Maps', more: 'Show more',
    floor: 'Floor', garden: 'Garden', terrace: 'Terrace', progress: 'Progress', surface: 'Saleable area', price: 'Price', removed: 'Some saved apartments are no longer in the catalogue.',
  },
  ar: {
    title: 'ابحث عن شقتك', intro: 'قارن الشقق في تونس وصفاقس حسب الميزانية والمساحة واحتياجاتك.',
    search: 'المدينة أو الإقامة أو مرجع الشقة', city: 'المدينة', project: 'الإقامة', all: 'الكل', status: 'التوفر',
    bedrooms: 'غرف النوم (دون غرفة الجلوس)', minPrice: 'الميزانية الدنيا (د.ت)', maxPrice: 'الميزانية القصوى (د.ت)', minArea: 'المساحة الدنيا (م²)', maxArea: 'المساحة القصوى (م²)',
    available: 'متاحة', reserved: 'محجوزة', sold: 'مباعة', unconfirmed: 'التوفّر يحتاج إلى تأكيد', reset: 'إعادة ضبط', results: 'شقة', sort: 'ترتيب حسب', reference: 'المرجع',
    priceAsc: 'السعر تصاعدياً', priceDesc: 'السعر تنازلياً', areaAsc: 'المساحة تصاعدياً', areaDesc: 'المساحة تنازلياً', empty: 'لا توجد شقق مطابقة لهذه المعايير.', request: 'السعر عند الطلب', details: 'تفاصيل الشقة',
    favourite: 'إضافة إلى المفضلة', unfavourite: 'حذف من المفضلة', compare: 'مقارنة', compared: 'حذف من المقارنة',
    selection: 'اختياراتي', favourites: 'المفضلة', comparison: 'المقارنة', maxCompare: 'يمكن مقارنة ثلاث شقق كحد أقصى. احذف شقة لإضافة أخرى.',
    savedHere: 'تُحفظ اختياراتك على هذا الجهاز.', noSaved: 'لم تختر أي شقة بعد. أضف شققاً من البحث أو من صفحة التفاصيل.', storageError: 'اختياراتك متاحة في هذه النافذة ولكن المتصفح لا يسمح بحفظها.',
    visit: 'طلب زيارة', map: 'عرض الخريطة', mapHint: 'موقع تقريبي حسب العنوان. يؤكد فريقنا مكان الموعد بدقة.', mapSelect: 'الإقامة المعروضة على الخريطة', mapExternal: 'فتح في خرائط Google', more: 'عرض المزيد',
    floor: 'الطابق', garden: 'الحديقة', terrace: 'الشرفة', progress: 'التقدم', surface: 'المساحة القابلة للبيع', price: 'السعر', removed: 'بعض الشقق المحفوظة لم تعد ضمن الكتالوج.',
  },
};
